export const CHANGE_DISCOUNT = "home/change_discount"
export const CHANGE_HOT_RECOMMEND = "home/change_hot_recommend"
export const CHANGE_LONGFOR = "home/change_longfor"
export const CHANGE_HIGHSCORE = "home/change_highscore"
export const CHANGE_GOODPRICE = "home/change_goodprice"
export const CHANGE_PLUS = "home/change_plus"
