# 多阶段构建不会生成src文件只会打包build之后的项目

# build stage
FROM node:18 as build-stage

WORKDIR /app

COPY package.json .

RUN npm config set registry https://registry.npmmirror.com/

RUN npm install

COPY . .

RUN npm run build

# production stage
FROM node:18 as production-stage

COPY --from=build-stage /app/dist /app
COPY --from=build-stage /app/package.json /app/package.json

WORKDIR /app

RUN npm install --production

EXPOSE 3000

CMD ["node", "/app/main.js"]


# FROM 后面添加一个 as 来指定当前构建阶段的名字。

# 通过 COPY --from=xxx 可以从上个阶段复制文件过来。

# 然后 npm install 的时候添加 --production，这样只会安装 dependencies 的依赖。